Modules/Cms/Routes/web.php
<?php

use Modules\Cms\Http\Controllers\CmsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('cms')->group(function() {
    Route::get('/', 'CmsController@index');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.','middleware' => ['auth']], function () {
    Route::middleware('auth')->prefix('cmsCategory')->name('cmsCategory.')->group(function () {

        Route::get('/categoryList', [CmsController::class, 'categoryList'])->name('categoryList');
        Route::get('/add', [CmsController::class, 'add'])->name('add');
        Route::post('save', [CmsController::class, 'save'])->name('save');
        Route::get('edit', [CmsController::class, 'edit'])->name('edit');
        Route::post('update', [CmsController::class, 'update'])->name('update');
        Route::get('view', [CmsController::class, 'view'])->name('view');
        Route::get('delete', [CmsController::class, 'delete'])->name('delete');
            
    });  
    Route::middleware('auth')->prefix('cms')->name('cms.')->group(function () {
    
        Route::get('/cmsList', [CmsController::class, 'cmsList'])->name('cmsList');
        Route::get('/cmsTypeBasedList', [CmsController::class, 'cmsTypeBasedList'])->name('cmsTypeBasedList');
        Route::get('/addCms', [CmsController::class, 'addCms'])->name('addCms');
        Route::post('saveCms', [CmsController::class, 'saveCms'])->name('saveCms');
        Route::get('editCms', [CmsController::class, 'editCms'])->name('editCms');
        Route::post('updateCms', [CmsController::class, 'updateCms'])->name('updateCms');
        Route::get('viewCms', [CmsController::class, 'viewCms'])->name('viewCms');
        Route::get('deleteCms', [CmsController::class, 'deleteCms'])->name('deleteCms');
        Route::post('ckeditor_image_upload', [CmsController::class, 'ckeditor_image_upload'])->name('ckeditor_image_upload');
        Route::get('remove_file', [CmsController::class, 'removeFile'])->name('remove_file');
        Route::get('remove_logo', [CmsController::class, 'removeLogo'])->name('remove_logo');
        Route::get('remove_video', [CmsController::class, 'removeVideo'])->name('remove_video');
        Route::get('remove_image', [CmsController::class, 'removeImage'])->name('remove_image');
        Route::get('remove_doc', [CmsController::class, 'removeDoc'])->name('remove_doc');
        Route::get('remove_absolute_image', [CmsController::class, 'removeAbsoluteImage'])->name('remove_absolute_image');


        /*
        |--------------------------------------------------------------------------
        | Category Wise Listing
        */
        // Route::get('/patientStories', [CmsController::class, 'patientStories'])->name('patientStories');

        // Route::get('/patients_stories/{id?}', [CmsController::class, 'cmsList'])->name('list_patients_stories');
        // Route::get('/events/{id?}', [CmsController::class, 'cmsList'])->name('list_events');
        // Route::get('/blogs/{id?}', [CmsController::class, 'cmsList'])->name('list_blogs');
        // Route::get('/partners/{id?}', [CmsController::class, 'cmsList'])->name('list_partners');
        // Route::get('/awards/{id?}', [CmsController::class, 'cmsList'])->name('list_awards');
        // Route::get('/our-team/{id?}', [CmsController::class, 'cmsList'])->name('list_our_team');
        // Route::get('/patient-testimonial/{id?}', [CmsController::class, 'cmsList'])->name('list_patients_testimonial');
        // Route::get('/partners-testimonial/{id?}', [CmsController::class, 'cmsList'])->name('list_partners_testimonial');
    });  
});

Modules/Cms/Entities/CmsCategory.php
<?php

namespace Modules\Cms\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class CmsCategory extends Model
{
    use HasFactory;

    protected $fillable = ['id','title','parent_id','is_editable'];
    
    protected static function newFactory()
    {
        return \Modules\Cms\Database\factories\CmsCategoryFactory::new();
    }
}

Modules/Cms/Models/CmsCategory.php
<?php

namespace Modules\Cms\Models;


use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CmsCategory extends Model
{
    use HasFactory;
    protected $table = 'cms_categories';

    protected $fillable = [
        'id','title','parent_id','is_editable'
    ];
    public function cms()
    {
        return $this->hasMany('Modules\Cms\Models\Cms');
    }
   
}

Modules/Cms/Http/Controllers/Includes/CmsCategory.php
<?php

namespace Modules\Cms\Http\Controllers\Includes;
use Modules\Cms\Http\Requests\CmsCategory\CmsCategoryAddRequest;
use Modules\Cms\Http\Requests\CmsCategory\CmsCategorySaveRequest;
use Modules\Cms\Http\Requests\CmsCategory\CmsCategoryEditRequest;
use Modules\Cms\Http\Requests\CmsCategory\CmsCategoryUpdateRequest;
use Modules\Cms\Http\Requests\CmsCategory\CmsCategoryViewRequest;
use Modules\Cms\Http\Requests\CmsCategory\CmsCategoryDeleteRequest;
use Modules\Cms\Repositories\Includes\CmsCategory\CmsCategoryRepositoryInterface as CmsCategoryRepository;
use Illuminate\Http\Request;
trait CmsCategory
{
    public function categoryList(CmsCategoryRepository $cmsCategoryRepo)
    {  
        $cmsCategory = $cmsCategoryRepo->all();                           
        return view('cms::cmsCategory.listCmsCategory', compact('cmsCategory'));           
    }

    public function add(CmsCategoryAddRequest $request)
    {  
        return view('cms::cmsCategory.addCmsCategory');
    }

    public function save(CmsCategorySaveRequest $request, CmsCategoryRepository $cmsCategoryRepo)
    {       
        $inputData = [
            'title'  => $request->title,
        ];
        $cmsCategory = $cmsCategoryRepo->save($inputData);  
        connectify('success', 'Success!', 'Cms Category added successfully');                              
        return redirect()
            ->route('admin.cmsCategory.categoryList');   
    } 

    public function view(CmsCategoryViewRequest $request,CmsCategoryRepository $cmsCategoryRepo)
    { 
        $cmsCategory = $cmsCategoryRepo->get($request->id);  
        return view('cms::cmsCategory.viewCmsCategory', compact('cmsCategory'));
    }

    public function edit(CmsCategoryEditRequest $request,CmsCategoryRepository $cmsCategoryRepo)
    {   
        $cmsCategory = $cmsCategoryRepo->get($request->id);  
        return view('cms::cmsCategory.editCmsCategory', compact('cmsCategory'));
    }

    public function update(CmsCategoryUpdateRequest $request, CmsCategoryRepository $cmsCategoryRepo)
    {   
        $inputData = [
            'id' => $request->id,            
            'title' => $request->title,
        ];

        $cmsCategory = $cmsCategoryRepo->update($inputData);
        connectify('success', 'Success!', 'Cms Category updated successfully');                              
        return redirect()
            ->route('admin.cmsCategory.categoryList');
    }

    public function delete(CmsCategoryRepository $cmsCategoryRepo, CmsCategoryDeleteRequest $request)
    { 
        if ($cmsCategoryRepo->delete($request->id)) {
            connectify('success', 'Success!', 'Cms Category deleted successfully');                              
            return redirect()
            ->route('admin.cmsCategory.categoryList');
        }
        return response()->json(['status' => 0, 'message' => "failed"]);
    }
    
}

Modules/Cms/Resources/views/cmsCategory/addCmsCategory.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
   {{ trans('panel.add_cms_category') }}
        
    </div>

    <div class="card-body">
        <form action="{{ route("admin.cmsCategory.save") }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                <label for="title"> {{ trans('panel.title') }}<i class="mdi mdi-flag-checkered text-danger "></i></label>
                <input type="text" id="title" name="title" class="form-control" value="{{old('title')}}" >
                @if($errors->has('title'))
                    <em class="invalid-feedback">
                        {{ $errors->first('title') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.user.fields.name_helper') }}
                </p>
            </div>  
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>


    </div>
</div>
@endsection
@section('scripts')
@parent

<script>
    $(document).ready(function() {
            $("#rating").select2({
                placeholder: "Select Rating",
                allowClear: true
            });
            $("#department").select2({
                placeholder: "Select Department",
                allowClear: true
            });
        });
</script>
@endsection

Modules/Cms/Resources/views/cmsCategory/editCmsCategory.blade.php
@extends('layouts.admin')
@section('content')

<style>
    input[type="number"] {
    -webkit-appearance: textfield;
    -moz-appearance: textfield;
    appearance: textfield;
    }
    
    input[type=number]::-webkit-inner-spin-button,
    input[type=number]::-webkit-outer-spin-button {
      -webkit-appearance: none;
    }
    
    .number-input {
      border: 2px solid #ddd;
      display: inline-flex;
    }
    
    .number-input,
    .number-input * {
      box-sizing: border-box;
    }
    
    .number-input button {
      outline:none;
      -webkit-appearance: none;
      background-color: transparent;
      border: none;
      align-items: center;
      justify-content: center;
      width: 3rem;
      height: 2rem;
      cursor: pointer;
      margin: 0;
      position: relative;
    }
    
    .number-input button:before,
    .number-input button:after {
      display: inline-block;
      position: absolute;
      content: '';
      width: 1rem;
      height: 2px;
      background-color: #212121;
      transform: translate(-50%, -50%);
    }
    .number-input button.plus:after {
      transform: translate(-50%, -50%) rotate(90deg);
    }
    
    .number-input input[type=number] {
      font-family: sans-serif;
      max-width: 3rem;
      padding: .5rem;
      border: solid #ddd;
      border-width: 0 2px;
      font-size: 1rem;
      height: 2rem;
      font-weight: bold;
      text-align: center;
    }
    i.mdi.mdi-minus {
        width: 2rem;
        text-align: center;
        line-height: 30px;
    }
    i.mdi.mdi-plus {
        width: 2rem;
        text-align: center;
        line-height: 30px;
    }
    span.on {
        width: 95px;
        float: left;
    }
    .custom-switch {
        padding-left: 0;
    }
    .custom-switch .custom-control-label::before{
        width: 2rem;
    }
    .custom-switch .custom-control-label::after {
        width: calc(1.3rem - 4px);
        }
    .badge-contr span.off {
        width: 70px;
        float: left;
    }
    .badge-contr span.on {
        float: none;
    }
    </style>


<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('panel.doctor') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.cmsCategory.update") }}" method="POST" enctype="multipart/form-data">
            @csrf 
            <input type="hidden" name="id" value="{{$cmsCategory->id}}">
            <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                <label for="title">Title*</label>
                <input type="text" id="title" name="title" class="form-control" value="{{ old('title', isset($cmsCategory) ? $cmsCategory->title : '') }}" required>
                @if($errors->has('title'))
                    <em class="invalid-feedback">
                        {{ $errors->first('title') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.user.fields.name_helper') }}
                </p>
            </div> 
            
            
            <div class="col-md-6 badge-contr">
                <div class="form-group {{ $errors->has('status') ? 'has-error' : '' }}">
                <label for="status">Status</label>
                    <div class="custom-control custom-switch">
                        <input type="checkbox" {{ old('status',$cmsCategory->status == 1) ? "checked" : "" }} class="custom-control-input" id="status" name="status">
                        <span class="off">No</span>
                        <label class="custom-control-label" for="status"></label>
                        <span class="on">Yes</span>
                    </div>
                </div> 
            </div>   
            </div>
            <br>       
            
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>


    </div>
</div>
@endsection
@section('scripts')
@parent

<script>
    $(document).ready(function() {
            $("#rating").select2({
                placeholder: "Select Rating",
                allowClear: true
            });
            $("#department").select2({
                placeholder: "Select Rating",
                allowClear: true
            });
        });
</script>
@endsection

Modules/Cms/Resources/views/cmsCategory/listCmsCategory.blade.php
@extends('layouts.admin')
@section('content')
<!-- @can('cms_category_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.cmsCategory.add") }}">
                <i class="mdi mdi-plus"></i> 
                Add Cms Category
            </a>
        </div>
    </div>
@endcan -->
<div class="card">
    <div class="card-header">
       List Cms Category
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-User">
                <thead>
                    <tr>
                        <th width="10"></th>
                        <th>{{ trans('cruds.user.fields.id') }}</th>
                        <th>Title </th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($cmsCategory as $key => $category)
                        <tr data-entry-id="{{ $category->id }}">
                            <td></td>
                            <td> {{ $key+1 }}</td>
                            <td> {{ $category->title ?? '' }}</td>   
                            <td> 
                            @can('cms_category_show')                               
                                <a class="btn btn-xs btn-primary" href="{{ route('admin.cmsCategory.view', ['id' => $category->id]) }}">
                                    {{ trans('global.view') }}
                                </a>   
                            @endcan
                            @can('cms_category_edit')     
                                <a class="btn btn-xs btn-info d-none" href="{{route('admin.cmsCategory.edit', ['id' => $category->id]) }}">
                                    {{ trans('global.edit') }}
                                </a>                             
                            @endcan
                            @can('cms_category_delete')    
                                <form action="{{ route('admin.cmsCategory.delete',  ['id' => $category->id]) }}" 
                                    onsubmit="return confirm('{{ trans('global.areYouSure') }}');" 
                                    style="display:none;">
                                    <input type="hidden" name="id" value="{{$category->id}}">
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                    <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                </form>
                            @endcan    
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>


    </div>
</div>
@endsection
@section('scripts')
@parent
<script>
    $(function () {
    let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
    $.extend(true, $.fn.dataTable.defaults, {
        order: [[ 1, 'asc' ]],
        pageLength: 100,
    });
    $('.datatable-User:not(.ajaxTable)').DataTable({ buttons: dtButtons })
        $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
            $($.fn.dataTable.tables(true)).DataTable()
                .columns.adjust();
        });
})

</script>
@endsection

Modules/Cms/Resources/views/cmsCategory/viewCmsCategory.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        View cms Category
    </div>
    <div class="card-body">
        <div class="mb-2">
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr> 
                        <th>
                            {{ trans('cruds.user.fields.id') }}
                        </th>
                        <td>
                            {{ $cmsCategory->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.user.fields.name') }}
                        </th>
                        <td>
                            {{ $cmsCategory->title }}
                        </td>
                    </tr>
                   
                </tbody>
            </table>
            <a style="margin-top:20px;" class="btn btn-default" href="{{ url()->previous() }}">
                {{ trans('global.back_to_list') }}
            </a>
        </div>


    </div>
</div>
@endsection