Modules/Videos/Routes/web.php
<?php
use Modules\Videos\Http\Controllers\VideosController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('videos')->group(function() {
    Route::get('/', 'VideosController@index');
});


Route::group(['prefix' => 'admin', 'as' => 'admin.','middleware' => ['auth']], function () {
    Route::middleware('auth')->prefix('videossections')->name('videossections.')->group(function () {
        Route::get('/videoSectionList', [VideosController::class, 'videoSectionList'])->name('videoSectionList');
        Route::get('addVideoSections', [VideosController::class, 'addVideoSections'])->name('addVideoSections');
        Route::post('saveVideoSections', [VideosController::class, 'saveVideoSections'])->name('saveVideoSections');
        Route::get('editVideoSections', [VideosController::class, 'editVideoSections'])->name('editVideoSections');
        Route::post('updateVideoSections', [VideosController::class, 'updateVideoSections'])->name('updateVideoSections');
        Route::get('viewVideoSections', [VideosController::class, 'viewVideoSections'])->name('viewVideoSections');
        Route::get('deleteVideoSections', [VideosController::class, 'deleteVideoSections'])->name('deleteVideoSections');   
            
    });  
    Route::middleware('auth')->prefix('videos')->name('videos.')->group(function () {
    
        Route::get('/videoList', [VideosController::class, 'videoList'])->name('videoList');
        Route::get('/addVideos', [VideosController::class, 'addVideos'])->name('addVideos');
        Route::post('saveVideos', [VideosController::class, 'saveVideos'])->name('saveVideos');
        Route::get('editVideos', [VideosController::class, 'editVideos'])->name('editVideos');
        Route::post('updateVideos', [VideosController::class, 'updateVideos'])->name('updateVideos');
        Route::get('viewVideos', [VideosController::class, 'viewVideos'])->name('viewVideos');
        Route::get('deleteVideos', [VideosController::class, 'deleteVideos'])->name('deleteVideos');
        Route::get('remove_video', [VideosController::class, 'removeVideo'])->name('remove_video');
        Route::get('remove_file', [VideosController::class, 'removeFile'])->name('remove_file');
        Route::get('remove_doc', [VideosController::class, 'removeDoc'])->name('remove_doc');
        Route::get('remove_author_image', [VideosController::class, 'removeAuthorImage'])->name('remove_author_image');

    });  
});

Modules/Videos/Entities/Videos.php
<?php

namespace Modules\Videos\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Videos extends Model
{
    use HasFactory;

    protected $fillable =  ['id','title','type','link','file','image','videos_sections_id','status','author','author_image','description','video_description'];
    
    protected static function newFactory()
    {
        return \Modules\Videos\Database\factories\VideosFactory::new();
    }
}

Modules/Videos/Models/Videos.php
<?php

namespace Modules\Videos\Models;


use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
 

class Videos extends Model
{
    use HasFactory;
    protected $table = 'videos';

    protected $fillable = [
        'id',
        'title',
        'type',
        'link',
        'file',
        'image',
        'videos_sections_id',
        'status',
        'author',
        'author_image',
        'description',
        'video_description'
    ];

    /**
     * Get all of the owning commentable models.
     */
    public function videoable()
    {
        return $this->morphTo();
    }
    public function videosections()
    {
        return $this->belongsTo('Modules\Videos\Models\VideosSections',  'videos_sections_id', 'id');
    }


}

Modules/Videos/Http/Controllers/Includes/Videos.php
<?php

namespace Modules\Videos\Http\Controllers\Includes;
use Modules\Videos\Http\Requests\Videos\VideosAddRequest;
use Modules\Videos\Http\Requests\Videos\VideosSaveRequest;
use Modules\Videos\Http\Requests\Videos\VideosEditRequest;
use Modules\Videos\Http\Requests\Videos\VideosUpdateRequest;
use Modules\Videos\Http\Requests\Videos\VideosViewRequest;
use Modules\Videos\Http\Requests\Videos\VideosDeleteRequest;
use Modules\Videos\Repositories\Includes\Videos\VideosRepositoryInterface as VideosRepository;
use Modules\Videos\Repositories\Includes\VideosSections\VideosSectionsRepositoryInterface as VideosSectionsRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Cohensive\Embed\Facades\Embed;
use League\CommonMark\Inline\Parser\EscapableParser;

trait Videos
{
   
    public function videoList(VideosRepository $videosRepo)
    { 
        $videos = $videosRepo->getForDatatable();   
        return view('videos::Videos.listVideos', compact('videos'));   
    } 

    public function addVideos(VideosAddRequest $request, VideosRepository $videosRepo, VideosSectionsRepository $videosectionRepo)
    {   
        $videoSection = $videosectionRepo->all(); 
        return view('videos::Videos.addVideos', compact('videoSection'));      
    }

    public function saveVideos(VideosSaveRequest $request, VideosRepository $videosRepo)
    {   
        if($request->type == "vimeo" || $request->type =="youtube"){
            if(preg_match('/https:\/\/(www\.)*vimeo\.com\/.*/',$request->link)){
                $request->link = $request->link;
            } 
            elseif(preg_match('/https:\/\/(www\.)*youtube\.com\/.*/',$request->link)){
                $request->link = $request->link;
            } 
            else{
                connectify('failed', 'Faild!', 'Enter valid url');                 
                return redirect()
                ->route('admin.videos.addVideos');
            }
        }
        $imageUrl = $request->hasFile('image')?Storage::disk('public')->putFile('video_image/',$request->file('image')):"";
        $fileUrl = $request->hasFile('file')?Storage::disk('public')->putFile('video_files/',$request->file('file')):""; 
        $authorImage = $request->hasFile('author_image')?Storage::disk('public')->putFile('author_image/',$request->file('author_image')):""; 

         $inputData = [
            'title'  => $request->title,
            'videos_sections_id'  => $request->section_id,
            'link'  => $request->link,
            'type'  => $request->type,
            'file'  => $fileUrl,
            'image'  => $imageUrl,
            'author'  => $request->author,
            'description' => $request->description,
            'author_image'  => $authorImage,
            'video_description' =>$request->video_description
        ];
        $videos = $videosRepo->save($inputData); 
        connectify('success', 'Success!', 'Videos added successfully');                 
            return redirect()
            ->route('admin.videos.videoList');
    }     

    public function viewVideos(VideosViewRequest $request,VideosRepository $videosRepo, VideosSectionsRepository $videosectionRepo)
    {  
        $videos = $videosRepo->get($request->id);  
        $section = $videosectionRepo->get($videos->videos_sections_id); 
        return view('videos::Videos.viewVideos', compact('videos','section'));
    }

    public function editVideos(VideosEditRequest $request,VideosRepository $videosRepo, VideosSectionsRepository $videosectionRepo)
    {   
        $videos = $videosRepo->get($request->id); 
        $section = $videosectionRepo->all();
        return view('videos::Videos.editVideos', compact('videos','section'));
    }

    public function updateVideos(VideosUpdateRequest $request, VideosRepository $videosRepo)
    {  
        $inputData = [
            'id'  => $request->id,
            'title'  => $request->title,
            'videos_sections_id'  => $request->section_id,
            'author' =>$request->author,
            'description' => $request->description,
            'video_description' =>$request->video_description
        ];

        if(isset($request->status)){ 
            $inputData['status']=($request->status == "on")?1:0;
        }else{ 
            $inputData['status']='0';
        }
 
        if ($request->link) { 
            $inputData['link'] = $request->link;
        }

        if ($request->hasFile('image')) { 
            $this->_removeFile($videosRepo, $request->id);                 
            $imageUrl = Storage::disk('public')->putFile('video_image/',$request->file('image'));
            $inputData['image'] = $imageUrl;
        } 

        if ($request->hasFile('file')) { 
            $this->_removeFile($videosRepo, $request->id);                 
            $fileUrl = Storage::disk('public')->putFile('video_files/',$request->file('file'));
            $inputData['file'] = $fileUrl;
        } 

        if ($request->hasFile('author_image')) { 
            $this->_removeAuthorImage($videosRepo, $request->id);                 
            $fileUrl = Storage::disk('public')->putFile('author_image/',$request->file('author_image'));
            $inputData['author_image'] = $fileUrl;
        } 
        
        $videosRepo->update($inputData);
        connectify('success', 'Success!', 'Videos Updated successfully');               
        return redirect()
        ->route('admin.videos.videoList')
            ->with('success', 'Updated successfuly');
        
       
    }

     

    public function removeFile(VideosRepository $videoRepo,Request $request)
    {  
        if ($this->_removeFile($videoRepo, $request->id)) {
            $videoRepo->resetFile($request->id);
        }
        return redirect()
            ->route('admin.videos.editVideos', ['id' => $request->id])
            ->with('success', 'File deleted successfuly');
    }

    public function removeVideo(VideosRepository $videoRepo,Request $request)
    {    
        $videoRepo->resetVideo($request->id);
        connectify('success', 'Success!', 'File deleted successfully');               
        return redirect()
            ->route('admin.videos.editVideos', ['id' => $request->id]);
    }

    private function _removeFile($videoRepo, $id)
    { 
        $image = $videoRepo->get($id);
        if (Storage::disk('public')->delete($image->image)) {
            return true;
        }
        return false;
    }

    public function removeDoc(VideosRepository $videoRepo,Request $request)
    {    
        if ($this->_removeDoc($videoRepo, $request->id)) {
            $videoRepo->resetDoc($request->id);
        }
        connectify('success', 'Success!', 'File deleted successfully');               
        return redirect()
            ->route('admin.videos.editVideos', ['id' => $request->id]);
    }

    private function _removeDoc($videoRepo, $id)
    { 
        $image = $videoRepo->get($id);
        if (Storage::disk('public')->delete($image->file)) {
            return true;
        }
        return false;
    }

    public function deleteVideos(VideosRepository $videoRepo, VideosDeleteRequest $request)
    { 
        if ($videoRepo->delete($request->id)) {
            connectify('success', 'Success!', 'Videos deleted successfully');               
            return redirect()
            ->route('admin.videos.videoList');
        }
            return response()->json(['status' => 0, 'message' => "failed"]);
    }

    public function removeAuthorImage(VideosRepository $videoRepo,Request $request)
    {    
        if ($this->_removeAuthorImage($videoRepo, $request->id)) {
            $videoRepo->removeAuthorImage($request->id);
        }
        connectify('success', 'Success!', 'File deleted successfully');               
        return redirect()
            ->route('admin.videos.editVideos', ['id' => $request->id]);
    }

    private function _removeAuthorImage($videoRepo, $id)
    { 
        $image = $videoRepo->get($id); 
        if (Storage::disk('public')->delete($image->author_image)) {
            return true;
        }
        return false;
    }
    
}

Modules/Videos/Http/Controllers/VideosController.php
<?php

namespace Modules\Videos\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Routing\Controller;
use Modules\Videos\Http\Controllers\Includes\Videos;
use Modules\Videos\Http\Controllers\Includes\VideosSections;

class VideosController extends Controller
{
    use Videos;
    use VideosSections;
}

Modules/Videos/Resources/views/Videos/addVideos.blade.php
@extends('layouts.admin')
@section('content')
<script src="//cdn.ckeditor.com/4.14.1/standard/ckeditor.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<html>
<body>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<div class="card">
    <div class="card-header">
        Add Video  
    </div>

    <div class="card-body">
        <form action="{{ route("admin.videos.saveVideos") }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                        <label for="title">Title<i class="mdi mdi-flag-checkered text-danger "></i></label>
                        <input type="text" id="title" name="title" class="form-control" value="{{old('title')}}" >
                        @if($errors->has('title'))
                            <em class="invalid-feedback">
                                {{ $errors->first('title') }}
                            </em>
                        @endif
                        <p class="helper-block">
                            {{ trans('cruds.user.fields.name_helper') }}
                        </p>
                    </div> 
                </div>
                <div class="col-md-6">
                    <div class="form-group {{ $errors->has('section_id') ? 'has-error' : '' }}">
                        <label for="section_id">Choose Section <i class="mdi mdi-flag-checkered text-danger "></i></label>
                            <select id="section_id" name="section_id" class="js-states form-control">
                                <option value="">{{ trans('panel.select') }}</option>
                                @foreach($videoSection as $data) 
                                <option value="{{$data->id}}" name="section_id-dropdown" id="section_id-dropdown" onclick="myFunction()" >
                                {{$data->name}}
                                </option>
                                @endforeach
                            </select> 
                            @if($errors->has('section_id'))
                            <em class="invalid-feedback">
                                {{ $errors->first('section_id') }}
                            </em>
                        @endif              
                        <p class="helper-block">
                        {{ trans('cruds.user.fields.name_helper') }}
                        </p>
                    </div>     
                </div>
            </div>
            <div class="row">
           
                <div class="col-md-6">
                    <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                        <label for="name">Type</label>
                            <select id="type" name="type" class="js-states form-control" onchange="change_type()">
                               <option value="">Choose:</option>
                                <option value="vimeo">Vimeo</option>
                                <option value="youtube">Youtube</option>
                                <option value="file">File</option>
                            </select>               
                        <p class="helper-block">
                        {{ trans('cruds.user.fields.name_helper') }}
                        </p>
                    </div>     
                 
                </div>
                <div class="col-md-6" id="toshow">
                <div class="form-group {{ $errors->has('link') ? 'has-error' : '' }}">
                        <label for="link">Link<i class="mdi mdi-flag-checkered text-danger "></i></label>
                        <input type="text" id="link" name="link" class="form-control" value="{{old('link')}}" >
                        @if($errors->has('link'))
                            <em class="invalid-feedback">
                                {{ $errors->first('link') }}
                            </em>
                        @endif
                        <p class="helper-block">
                            {{ trans('cruds.user.fields.name_helper') }}
                        </p>
                    </div>    
                </div>

                <div class="col-md-6" id="toshow2">
                    <div class="form-group {{ $errors->has('file') ? 'has-error' : '' }}">
                        <label for="file"> File<i class="mdi mdi-flag-checkered text-danger "></i> </label>
                            <input type="file" name="file" id="input-file-now-banner" class="dropify validate" data-default-file="" accept="application/pdf,application/doc,application/docx" /> 
                            @if($errors->has('file'))
                            <em class="invalid-feedback">
                                {{ $errors->first('file') }}
                            </em>
                            @endif
                            <p class="helper-block">
                            {{ trans('cruds.user.fields.name_helper') }}
                            </p>
                    </div>   
                </div>
            </div>

            <div class="row" >

                <div class="col-md-6" id="toshow1">
                    <div class="form-group {{ $errors->has('image') ? 'has-error' : '' }}">
                        <label for="image">Thumb Line Images<i class="mdi mdi-flag-checkered text-danger "></i> </label>
                            <input type="file" name="image" id="input-file-now-banner" class="dropify validate" data-default-file="" accept= 'image/jpeg , image/jpg, image/gif, image/png' />
                            @if($errors->has('image'))
                            <em class="invalid-feedback">
                                {{ $errors->first('image') }}
                            </em>
                            @endif
                            <p class="helper-block">
                            {{ trans('cruds.user.fields.name_helper') }}
                                </p>
                    </div>         
                </div>
                <div class="col-md-6">
               
                </div>

               
            </div>  
            
            <div class="row">
                <div class="col-md-12"> 
                <div class="form-group {{ $errors->has('video_description') ? 'has-error' : '' }}">
                <label for="video_description"> Video Description</label>
                <textarea class="ckeditor form-control" id="video_description" name="video_description" required>
                {!! old('video_description', isset($department) ? $department->video_description : '') !!}
                </textarea>      

                @error('content')<small class="form-text text-danger">{{ $message }}</small>@enderror
                @if($errors->has('department'))
                    <em class="invalid-feedback">
                        {{ $errors->first('department') }}
                    </em>
                @endif
            </div> 
                </div>
            </div>
            
            <div class="row" >
                <div class="col-md-6" >
                    <div class="form-group {{ $errors->has('author') ? 'has-error' : '' }}">
                        <label for="author">Author</label>
                        <input type="text" id="author" name="author" class="form-control" value="{{old('author')}}" >
                        @if($errors->has('author'))
                            <em class="invalid-feedback">
                                {{ $errors->first('author') }}
                            </em>
                        @endif
                        <p class="helper-block">
                            {{ trans('cruds.user.fields.name_helper') }}
                        </p>
                    </div>   
                </div>
                
                <div class="col-md-6" >
                    <div class="form-group {{ $errors->has('author_image') ? 'has-error' : '' }}">
                        <label for="author_image">Author Image </label><br>
                            <input type="file" name="author_image" id="input-file-now-banner" class="dropify validate" data-default-file="" accept= 'image/jpeg , image/jpg, image/gif, image/png' />
                            @if($errors->has('author_image'))
                            <em class="invalid-feedback">
                                {{ $errors->first('author_image') }}
                            </em>
                            @endif
                    </div>   
                </div>
            </div>

            <div class="row">
                <div class="col-md-12"> 
                <div class="form-group {{ $errors->has('description') ? 'has-error' : '' }}">
                <label for="description"> {{ trans('panel.description') }}</label>
                <textarea class="ckeditor form-control" id="description" name="description" required>
                {!! old('description', isset($department) ? $department->description : '') !!}
                </textarea>      

                @error('content')<small class="form-text text-danger">{{ $message }}</small>@enderror
                @if($errors->has('department'))
                    <em class="invalid-feedback">
                        {{ $errors->first('department') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.user.fields.name_helper') }}
                </p>
            </div> 
                </div>
            </div>
           
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>


    </div>
</div>
@endsection
@section('scripts')
@parent

<script>
    $(document).ready(function() {
            $("#section_id").select2({
                placeholder: "Select Video Section",
                allowClear: true
            });
            $("#type").select2({
                placeholder: "Choose Type",
                allowClear: true
            });
           
           
        });

         
</script>
<script src="//cdn.ckeditor.com/4.14.1/standard/ckeditor.js"></script>

<script> 
    $("#toshow").hide(); 
    $("#toshow1").hide();  
    $("#toshow2").hide();  

    function change_type(){
        var type =$("#type").val();
            if(type == 'vimeo' || type =="youtube"){
                $("#toshow").show();
                $("#toshow1").show();
                $("#toshow2").hide();

            }else{
                $("#toshow").hide();
                $("#toshow1").hide();
                $("#toshow2").show();
            }    
    }   
</script>
@endsection

Modules/Videos/Resources/views/Videos/listVideos.blade.php
@extends('layouts.admin')
@section('content')
@can('videos_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.videos.addVideos") }}">
                <i class="mdi mdi-plus"></i>
               Add Videos  
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        List Videos  
   
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-User">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.user.fields.id') }}
                        </th>
                        <th>
                        Title
                        </th>
                        <th>Status </th>
                       
                        <th>
                            {{ trans('cruds.user.fields.roles') }}
                        </th>
                       
                    </tr>
                </thead>
                <tbody>
                    @foreach($videos as $key => $video)
                        <tr data-entry-id="{{ $video->id }}">
                            <td></td>
                            <td>{{ $key+1 }}</td>
                            <td>{{ $video->title }}</td>
                            <td>
                                @if($video->status == 1)
                                    <i class="mdi mdi-checkbox-marked-circle-outline btn-success"></i>
                                    Active
                                @else
                                    <i class="mdi mdi-close-circle-outline btn-danger"></i>
                                    In Active
                                @endif
                            </td>
                            <td> 
                            @can('videos_show')              
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.videos.viewVideos', ['id' => $video->id]) }}">
                                        {{ trans('global.view') }}
                                    </a> 
                            @endcan
                            @can('videos_edit') 
                                    <a class="btn btn-xs btn-info" href="{{route('admin.videos.editVideos', ['id' => $video->id]) }}">
                                        {{ trans('global.edit') }}
                                    </a>                             
                            @endcan
                            @can('videos_delete')    
                                    <form action="{{ route('admin.videos.deleteVideos',  ['id' => $video->id]) }}" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="id" value="{{$video->id}}">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                            @endcan        
                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection
@section('scripts')
@parent
<script>
    $(function () {
    let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
    $.extend(true, $.fn.dataTable.defaults, {
        order: [[ 1, 'asc' ]],
        pageLength: 100,
    });
    $('.datatable-User:not(.ajaxTable)').DataTable({ buttons: dtButtons })
        $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
            $($.fn.dataTable.tables(true)).DataTable()
                .columns.adjust();
        });
})

</script>
@endsection

Modules/Videos/Resources/views/Videos/viewVideos.blade.php
@extends('layouts.admin')
@section('content')
<style>
    .table.video-table th img, .table.video-table td img {
    width: 80px;
    height: 80px;
    border-radius: 10px;
}
</style>
<div class="card">
    <div class="card-header">
       View Video 
    </div>
    <div class="card-body">
        <div class="mb-2">
            <table class="table table-bordered table-striped video-table">
                <tbody>
                    <tr>
                        <th>
                            Name
                        </th>
                        <td>
                            {{ $videos->title }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Video Section
                        </th>
                        <td>
                            {{ $section->name }}
                        </td>
                    </tr>
                    @if($videos->link != null)
                    <tr>
                        <th>
                            Video
                        </th>
                        <td> 
                        {!! Embed::make($videos->link)->parseUrl()->getIframe() !!}
                       
                        </td>
                    </tr>
                    @endif
                    @if($videos->type =="youtube" || $videos->type =="vimeo")
                    <tr>
                        <th>
                            Image
                        </th>
                        <td> 
                        <img src="{{asset('storage/'.$videos->image)}}" alt="" width="1000px" height="500px">
                       
                        </td>
                    </tr>
                    @else 
                    <tr>
                        <th>
                           File
                        </th>
                        <td>                                                                                           
                            <a class="btn-floating mb-1 btn-flat waves-effect waves-light  pink accent-2 white-text" href="{{asset('storage/'.$videos->file)}}" target="_blank">
                                <i class="menu-icon mdi mdi-download" style="color: #000;font-size: 24px;"></i>
                            </a>                       
                        </td>
                    </tr>
                    @endif 
                   
                </tbody>
            </table>
            <a style="margin-top:20px;" class="btn btn-default" href="{{ url()->previous() }}">
                {{ trans('global.back_to_list') }}
            </a>
        </div>


    </div>
</div>
@endsection