Modules/Diseases/Routes/web.php
<?php
use Modules\Diseases\Http\Controllers\DiseasesController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('diseases')->group(function() {
    Route::get('/', 'DiseasesController@index');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.','middleware' => ['auth']], function () {
    Route::group(['prefix' => 'diseases', 'as' => 'diseases.'], function () {         
        Route::get('/listdiseases', [DiseasesController::class, 'listdiseases'])->name('listdiseases');
        Route::get('addDiseases', [DiseasesController::class, 'addDiseases'])->name('addDiseases');
        Route::post('save', [DiseasesController::class, 'save'])->name('save');
        Route::get('edit', [DiseasesController::class, 'edit'])->name('edit');
        Route::post('update', [DiseasesController::class, 'update'])->name('update');
        Route::get('view', [DiseasesController::class, 'view'])->name('view');
        Route::get('delete', [DiseasesController::class, 'delete'])->name('delete');       
    });

    Route::group(['prefix' => 'tips', 'as' => 'tips.'], function () {         
        // Route::get('/listdiseases', [DiseasesController::class, 'listdiseases'])->name('listdiseases');
        Route::get('addTips', [DiseasesController::class, 'addTips'])->name('addTips');
        Route::post('saveTips', [DiseasesController::class, 'saveTips'])->name('saveTips');
        Route::get('editTips', [DiseasesController::class, 'editTips'])->name('editTips');
        Route::post('updateTips', [DiseasesController::class, 'updateTips'])->name('updateTips');
        Route::get('viewTips', [DiseasesController::class, 'viewTips'])->name('viewTips');
        Route::get('deleteTips', [DiseasesController::class, 'deleteTips'])->name('deleteTips');       
        Route::get('remove_file', [DiseasesController::class, 'removeFile'])->name('remove_file');
    
    });
});

Modules/Diseases/Resources/views/partials/sections/basicDetails.blade.php
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
.checked {
  color: orange;
}
#pills-tabContent .table th, .table td {
    white-space: normal;
    line-height: 24px;
}
.table.video-table th, .table.video-table td {
    line-height: 24px;
    white-space: normal;
}
</style>
<div class="mb-2">
    <table class="table table-bordered table-striped video-table">
        <tbody>
            <tr>
                <th>{{ trans('cruds.user.fields.id') }}</th>
                <td>{{ $diseases->id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ $diseases->title }}</td>
            </tr>
            @if($diseases->related != null)
            <tr>
                <th>Related </th>
                <td>{{ $diseases->related }}</td>
            </tr>
            @endif
            @if($diseases->description != null)
            <tr>
                <th>Description</th>
                <td>{!! $diseases->description !!} </td>
            </tr>
            @endif
            @if($addedBy!= "")
            <tr>
                <th>Added By</th>
                <td>{{ $addedBy->first_name }}</td>
            </tr> 
            @endif 
        </tbody>
    </table>
</div>

Modules/Diseases/Resources/views/partials/sections/tipsDetails.blade.php
<style>
    table, th, td {
      border: 1px solid rgba(223, 217, 217, 0.918);
    }
    #example_filter input[type="search"]
    {
        border: 1px solid #ced4da;
        height: 1.75rem;
        padding: 0.5rem 0.81rem;
        font-size: 0.875rem;
        line-height: 1.5;
        border-radius: 0.2rem;
    }
    .table th, .table td {
        vertical-align: middle;
        font-size: 0.875rem;
        line-height: 1;
        white-space: nowrap;
        padding: 12px 15px;
    }

    </style>
<div class="card">
    <div class="card-header">
        Tips
        <a class="btn btn-warning float-right" href="{{route('admin.tips.addTips',['diseases_id' => $diseases->id])}}">
            Add Tips
        </a>
    </div> 

    <div class="card-body">
        <div class="table-responsive">
            <table id="example" class="display nowrap table" style="width:100%">
                <thead>
                    <tr>
                        <th>{{ trans('cruds.user.fields.id') }}</th>
                        <th>Title</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($tips as $key => $tip)
                        <tr data-entry-id="{{ $tip->id }}">
                            <td>{{ $key+1 }}</td>
                            <td>{{ $tip->title ?? '' }}</td>
                            <td>
                                @if($tip->status == 1)
                                    <i class="mdi mdi-checkbox-marked-circle-outline btn-success"></i>
                                    Active
                                @else
                                    <i class="mdi mdi-close-circle-outline btn-danger"></i>
                                    In Active
                                @endif
                            </td>
                            <td>
                                <a class="btn btn-xs btn-primary" href="{{ route('admin.tips.viewTips', ['id' => $tip->id,'diseases_id' => $diseases->id ]) }}">
                                    {{ trans('global.view') }}
                                </a> 

                                <a class="btn btn-xs btn-info" href="{{route('admin.tips.editTips', ['id' => $tip->id, 'diseases_id' => $diseases->id ]) }}">
                                    {{ trans('global.edit') }}
                                </a>   

                                <form action="{{ route('admin.tips.deleteTips',  ['id' => $tip->id]) }}" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                    <input type="hidden" name="id" value="{{$tip->id}}">
                                    <input type="hidden" name="diseases_id" value="{{$diseases->id}}">
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                    <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

    </div>
</div>


@section('scripts')
@parent
{{-- <script src="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css"></script> --}}
{{-- <script src="https://cdn.datatables.net/buttons/2.2.2/css/buttons.dataTables.min.css"></script> --}}
<script>
   $(document).ready(function() {
    $('#example').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            'copy', 'csv', 'excel', 'pdf', 'print'
        ]
    } );
} );

</script>
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
@endsection